name: YOLO Prod Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Deploy to YOLO Prod Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.YOLO_PROD_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd YoloService
            git pull origin main
            ./deploy-prod.sh